//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CE.Processors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CE.Processors.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1}.
        /// </summary>
        internal static string ApresentarNotas {
            get {
                return ResourceManager.GetString("ApresentarNotas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ********CAIXA ELETRÔNICO*********.
        /// </summary>
        internal static string AsteriscosCaixaEletronico {
            get {
                return ResourceManager.GetString("AsteriscosCaixaEletronico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **************************************.
        /// </summary>
        internal static string AsteriscosParaMenu {
            get {
                return ResourceManager.GetString("AsteriscosParaMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *************RELATÓRIO*************.
        /// </summary>
        internal static string AsteriscosRelatorio {
            get {
                return ResourceManager.GetString("AsteriscosRelatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite a quantidade de cédulas:.
        /// </summary>
        internal static string DigiteQuantidadeNota {
            get {
                return ResourceManager.GetString("DigiteQuantidadeNota", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o valor para saque:.
        /// </summary>
        internal static string DigiteValorSaque {
            get {
                return ResourceManager.GetString("DigiteValorSaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não tem notas suficientes..
        /// </summary>
        internal static string NotasInsuficientes {
            get {
                return ResourceManager.GetString("NotasInsuficientes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 - Deposito.
        /// </summary>
        internal static string OpcaoDeposito {
            get {
                return ResourceManager.GetString("OpcaoDeposito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 - Relatorio.
        /// </summary>
        internal static string OpcaoRelatorio {
            get {
                return ResourceManager.GetString("OpcaoRelatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 - Sair.
        /// </summary>
        internal static string OpcaoSair {
            get {
                return ResourceManager.GetString("OpcaoSair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 - Saque.
        /// </summary>
        internal static string OpcaoSaque {
            get {
                return ResourceManager.GetString("OpcaoSaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressione enter para continuar.....
        /// </summary>
        internal static string PressioneParaContinuar {
            get {
                return ResourceManager.GetString("PressioneParaContinuar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo total - R$ {0}.
        /// </summary>
        internal static string SaldoCarteira {
            get {
                return ResourceManager.GetString("SaldoCarteira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saque efetuado com sucesso. Você está mais pobre..
        /// </summary>
        internal static string SaldoEfetuado {
            get {
                return ResourceManager.GetString("SaldoEfetuado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o valor da cédula:.
        /// </summary>
        internal static string SelecionarCedula {
            get {
                return ResourceManager.GetString("SelecionarCedula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aqui não tem cheque especial, otário..
        /// </summary>
        internal static string SemSaldo {
            get {
                return ResourceManager.GetString("SemSaldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Total de {0} - R$ {1}.
        /// </summary>
        internal static string ValorTotalNotaRelatorio {
            get {
                return ResourceManager.GetString("ValorTotalNotaRelatorio", resourceCulture);
            }
        }
    }
}
